### ISSUE TITLE
Example Weather API Reached EOL

### ISSUE THREAD

**Issue by thecpdubguy** [apigee/apijam#55]
Weather API for this Lab in Appendix is no longer supported.

https://github.com/apigee/apijam/tree/master/Labs/Appendix/API%20Development%20-%20Hosted%20Targets/Lab%203%20-%20Doing%20more%20and%20Orchestration

Cause is query.yahooapis.com has reached EOL

https://github.com/googlecodelabs/your-first-pwapp/issues/144#issuecomment-451730466

I can work on a PR fix if wanted?

**Comment by aliceinapiland** [comment]
The current labs are different. Please check.
