### ISSUE TITLE
API proxy "as_Hipster-Products-API_rev1_2019_08_20.zip" pointing to broken URL

### ISSUE THREAD

**Issue by kalrasachin** [apigee/apijam#58]
The link under apijam/Module-3/Labs/Lab 1/ --> (Optional) Import Hipster Products API Proxy --> step (d) is broken. The following is the url for the same:

https://github.com/apigee/apijam/blob/master/Module-3/Labs/Lab%201/Resources/as_Hipster-Products-API_rev1_2019_08_15.zip

<img width="933" alt="Screen Shot 2019-10-26 at 07 52 03 AM" src="https://user-images.githubusercontent.com/48497213/67619144-f73b7e00-f7c5-11e9-84bb-1c90db201ca6.png">

**Comment by BaronMing1** [comment]
the link is not working , even trying with 08_15.zip or 08_20.zip

**Comment by tanatipint** [comment]
The link can not to Download.

**Comment by aliceinapiland** [comment]
Instructions changed.
