### ISSUE TITLE
Content changes due to product changes and labs updates

### ISSUE THREAD

**Issue by kurtkanaskie** [apigee/apijam#59]
New API proxy wizard UI, should change screen shots.
Uploading API proxy bundles has a known bug that the proxy doesn't get deployed if you select an environment.
Rest Client is gone, should update to use postman or curl

Module 2a Lab 1:
Step # 4 uses < UseEffectiveCount>true</ UseEffectiveCount> but talks about multiple MPs and counting, should explain use of this new property.

Module 2b:
At bottom of page shows links to labs followed by "Lets get started with Lab 1" which has a broken link.

**Comment by aliceinapiland** [comment]
Fixed
