### ISSUE TITLE
[codelabs-apigee-apijam]: URL not working

### ISSUE THREAD

**Issue by jrossthomson** [apigee/apijam#62]
URL appears to be unavailable: http://playground.apistudio.io/070cde0a-44f7-4e2c-8085-6e1020db7baf/spec

> wget http://playground.apistudio.io/070cde0a-44f7-4e2c-8085-6e1020db7baf/spec
> --2020-04-13 22:01:03--  http://playground.apistudio.io/070cde0a-44f7-4e2c-8085-6e1020db7baf/spec
> Resolving playground.apistudio.io (playground.apistudio.io)... failed: Name or service not known.
> wget: unable to resolve host address ‘playground.apistudio.io’

**Comment by aliceinapiland** [comment]
Fixed
