### ISSUE TITLE
Lab 4: Update screenshots/text for API catalog

### ISSUE THREAD

**Issue by rlorenzo** [apigee/apijam#67]
Go to https://github.com/apigee/apijam/tree/master/Module-1/Labs/Lab%204#publish-the-bronze-free-api-product-to-the-portal

The text and screenshot refer to selecting from the dropdown an option called "API". But in the current UI it is called "API catalog". Also, the text/image references a button called "Add API", but it is now just a plus button.

Following through the entire section, it seems all the text/images need to be updated as well.

**Comment by aliceinapiland** [comment]
Fixed.
